### ISSUE TITLE
Course Project issues/questions

### ISSUE THREAD

**Issue by jallemand** [Aelphy/ISC#11]
The link provided about mapreduce no longer works. Digging around the website it appears that it is no longer available.
(http://kosmiktechnologies.com/blog/hadoop-mapreduce-training-hyderabad/)

Also, this project is designed for groups and is not clear what the 40 points is based on should we work on it as individuals. The exercise suggests groups of 3, each completing 3 functions from the set of tools. Does that mean we are expected to only complete 3 functions for the full project score as individuals?

**Comment by Aelphy** [comment]
Thanks for pointing out the problem with the link.

if all the requirements are met - 40 points.
You can work alone, can form groups - the target is to develop a library which does its job.
In the case you are working alone - you still have to get my oks for each pull request (each task should be a pull request in the perfect world).
You cannot assume that individual can do one third of the job. It should be done by each group (group can be from 1 to 3 persons).
