### ISSUE TITLE
DFS and BFS notebook 5

### ISSUE THREAD

**Issue by rozniaka** [Aelphy/ISC#13]
Hi Mikhail, 

in notebook 5, what should be returned in the DFS and BFS algorithms?

**Comment by Aelphy** [comment]
they should be generators

**Comment by nandometzger** [comment]
I think the question is: what should DFS-generators return?
names of the visited nodes or minimum-spanning or something else? It is not clear in the description

**Comment by Aelphy** [comment]
They should return nodes
