### ISSUE TITLE
Question to assignment 7

### ISSUE THREAD

**Issue by rozniaka** [Aelphy/ISC#15]
In warming up part of TensorFlow, where we are supposed to calculate the sum of squared numbers, the result for the code implemented in python is different than code implemented in Tensorflow (when calculating for big integers). 

Up to 10**6, the result is the same, but with bigger numbers, the results do not match --> tensorflow returns number which is too small. As we discussed in a group of some students, is that an overflow error? Is there a way to allocate more memory per integer than int64 for tensorflow? 

I am talking about that example:

```
# "i will insert N here later"
N = tf.placeholder('int64', name="input_to_your_function")

# a recipe on how to produce {sum of squares of arange of N} given N
result = tf.reduce_sum((tf.range(N)**2))
```

**Comment by Aelphy** [comment]
It is indeed an overflow error. You could try to use float64 instead and see what happens
