### ISSUE TITLE
Link fail: assignment 2 - problem 5 - Folding-in technique

### ISSUE THREAD

**Issue by markkua** [Aelphy/ISC#18]
"Page Not Found" for link [https://berry.eecs.utk.edu/sc95/sc95.html](https://berry.eecs.utk.edu/sc95/sc95.html )  in `week2/Assignment2.ipynb` - `problem 5` - `Folding-in technique`

**Comment by Aelphy** [comment]
Thanks for reporting. Please use the following link instead https://dl.acm.org/doi/pdf/10.1145/224170.285569
