### ISSUE TITLE
Submit assignment via ETH Gitlab

### ISSUE THREAD

**Issue by caifazhou** [Aelphy/ISC#2]
Hello, Mihail,
I am trying to add you as the collaborator on [gitlab](https://gitlab.phys.ethz.ch/) (The ISG gitlab). But I cannot find you. Can you just register on this Gitlab platform so that I can add you? Thanks.

**Comment by Aelphy** [comment]
On ethz I am mikhailu.

But, I highly recommend you to use gitlab.com <http://gitlab.com/> or gitlab.ethz.ch <http://gitlab.ethz.ch/>

Sincerely,
Mikhail

**Comment by caifazhou** [comment]
@Aelphy Super. I've moved to gitlab.ethz.ch. Thanks.

**Comment by rozniaka** [comment]
I think I have the same problem. What is actually the difference between gitlab, github and gitlab.ethz? And actually gitlab.ethz.ch doesn't allow me to log in...

**Comment by Aelphy** [comment]
Those are different remote repository systems that work with GIT.
Github is older. Gitlab provides more features. On gitlab.ethz.ch you need to login with your nethz account.
