### ISSUE TITLE
Confusion in Assignment1

### ISSUE THREAD

**Issue by QD-HK** [Aelphy/ISC#4]
By the end of Problem1 in assigment1, you asked us to _"Measure times of multiplications by  T  for different values of  N  and plot them in loglog scale."_

I'm not sure what you want us to ask. By _times of multiplications_, do you want the number of multiplications of multiplying T with a vector, whose size is N?

Thank you very much!

Best,
Dai Qi

**Comment by jallemand** [comment]
Hi Dai, 

I believe the use of 'times' was meant more in the form of timing, as in how long a process will run. In this case, the time it takes for the convolutiions using T of different length (N) signals (or whatever the process was, I can't recall perfectly off the top of my head). That said, you could also argue that the number of times you had to multiply it with T would be proportional to the length of time.

Hope that helps.
Jon

**Comment by Aelphy** [comment]
Hi there.

Jon is right I want to see smth like a plot: runtime vs N

Sincerely,
Mikhail

**Comment by Aelphy** [comment]
That's also true, that you could carefully compute the number of unit operations (+-*/), but let's keep things practical :)
