### ISSUE TITLE
Workload of Assignment2

### ISSUE THREAD

**Issue by QD-HK** [Aelphy/ISC#6]
Dear Mikhail,

I have check the content of assignment 2 and found its workload is too heavy.

For me, I have spent 4 hrs solving the first question (fft). Although the line of code is less than 20 lines, but it really cost a lot of time to fully understand the algorithm.

I also talked with one classmate and he said he spent 8 hrs but was still far from finishing it. While 8 hrs was already too much for a course with 3 credit points.

I hope you could reconsider the assignment and may possibly postpone the deadline. For me I think assignment2 deserves at least 3 weeks in total, just like a small project...

Thank you very much!

Best,
Dai Qi

**Comment by Aelphy** [comment]
We will discuss that tomorrow in the class. If I find that everyone struggles from the same problem, I will have to postpone the deadline, probably not to give more material until this batch is done and not to give out the next assignment. Furthermore, we might spend more time on the seminar until everything with it is clear.
