### ISSUE TITLE
Seminar of week 5

### ISSUE THREAD

**Issue by caifazhou** [Aelphy/ISC#7]
Dear Mikhail,
I missed the seminar of the week and I am working on it now. I have two questions regarding it:
1. Do the points count as the grading of this seminar? If so can I get the points by submitting the seminar as an assignment?
2. Regarding the hyper-parameters optimization, do you plan to cover other approaches, e.g., Bayesian optimization, a sequential model-based optimization method for hyper-parameters optimization?  

BR,
Caifa

**Comment by Aelphy** [comment]
1. Yes
2. It is not in the plan.
